//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intentor.Yamapper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Intentor.Yamapper.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDbCommand created outside this provider..
        /// </summary>
        internal static string CommandCreatedOutsideProvider {
            get {
                return ResourceManager.GetString("CommandCreatedOutsideProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection is closed..
        /// </summary>
        internal static string ConnectionClosed {
            get {
                return ResourceManager.GetString("ConnectionClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem on database connection. Please check your configuration file..
        /// </summary>
        internal static string DatabaseConnectionException {
            get {
                return ResourceManager.GetString("DatabaseConnectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database connection &quot;{0}&quot; was not found. Please check your configuration file..
        /// </summary>
        internal static string DatabaseConnectionNotFound {
            get {
                return ResourceManager.GetString("DatabaseConnectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no defined database connection. Please check your configuration file..
        /// </summary>
        internal static string DatabaseConnectionsEmpty {
            get {
                return ResourceManager.GetString("DatabaseConnectionsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry not found..
        /// </summary>
        internal static string DataNotFoundException {
            get {
                return ResourceManager.GetString("DataNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities not mapped..
        /// </summary>
        internal static string EntitiesNotMapped {
            get {
                return ResourceManager.GetString("EntitiesNotMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity &quot;{0}&quot; is a View and does not have DELETE operation..
        /// </summary>
        internal static string EntityIsViewDelete {
            get {
                return ResourceManager.GetString("EntityIsViewDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity &quot;{0}&quot; is a View and does not have INSERT operation..
        /// </summary>
        internal static string EntityIsViewInsert {
            get {
                return ResourceManager.GetString("EntityIsViewInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity &quot;{0}&quot; is a View and does not have UPDATE operation..
        /// </summary>
        internal static string EntityIsViewUpdate {
            get {
                return ResourceManager.GetString("EntityIsViewUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity {0} not mapped..
        /// </summary>
        internal static string EntityNotMapped {
            get {
                return ResourceManager.GetString("EntityNotMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File contains validation errors..
        /// </summary>
        internal static string FileValidationException {
            get {
                return ResourceManager.GetString("FileValidationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace of file &quot;{0}&quot; is not supported: expected &quot;{1}&quot;..
        /// </summary>
        internal static string FileValidationExceptionNamespace {
            get {
                return ResourceManager.GetString("FileValidationExceptionNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation of file &quot;{0}&quot; failed: {1}.
        /// </summary>
        internal static string FileValidationExceptionSchema {
            get {
                return ResourceManager.GetString("FileValidationExceptionSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the expression is not an array for use on an operator IN..
        /// </summary>
        internal static string NotArrayOperatorIn {
            get {
                return ResourceManager.GetString("NotArrayOperatorIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A primary key for entity &quot;{0}&quot; was not found..
        /// </summary>
        internal static string PrimaryKeyNotFoundEntity {
            get {
                return ResourceManager.GetString("PrimaryKeyNotFoundEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A primary key was not found or not settled..
        /// </summary>
        internal static string PrimaryKeyNotFoundException {
            get {
                return ResourceManager.GetString("PrimaryKeyNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A primary key for table &quot;{0}&quot; was not found or not settled..
        /// </summary>
        internal static string PrimaryKeyNotFoundTable {
            get {
                return ResourceManager.GetString("PrimaryKeyNotFoundTable", resourceCulture);
            }
        }
    }
}
