/*********************************************
Generated by Intentor.Yamapper Class Generator
http://intentor.com.br/projects/yamapper/
*********************************************/
using System;
using System.Collections.Generic;

namespace Intentor.Examples.Model.Domain.Supertypes
{
    /// <summary>Supertype para Business Objects (Biz).</summary>
    /// <typeparam name="T">Tipo do objeto que representa o repositório de dados.</typeparam>
    public abstract class BizBase<T>
    {
        #region Construtor

        public BizBase(T dao)
        {
            _dao = dao;
        }

        #endregion

        #region Campos

        /// <summary>Data Access Object relacionado ao objeto de negócios.</summary>
        protected T _dao;

        #endregion
    }
}
