//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Intentor.Yamapper")]
[assembly: AssemblyDescription("Yet Another (.Net Based Database) Mapper.")]
[assembly: AssemblyCompany("Intentor")]
[assembly: AssemblyProduct("Intentor.Yamapper")]
[assembly: AssemblyCopyright("Copyright © 2009-2012 André Intentor Martins")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: Guid("eb3367a2-387b-4549-8434-8284130023fa")]
[assembly: AssemblyVersion("12.6.18.1905")]
[assembly: AssemblyFileVersion("12.6.18.1905")]


