/*********************************************
Generated by Intentor.Yamapper Class Generator
http://intentor.com.br/projects/yamapper/
*********************************************/
using System;
using System.Collections.Generic;
using Intentor.Yamapper;

namespace Intentor.Examples.Model.Data.Supertypes
{
    /// <summary>Supertype para Data Access Objects (Dao) que realizam  CRUD, utilizado para tabelas.</summary>
    /// <typeparam name="T">Tipo da entidade que representa a tabela do banco de dados.</typeparam>
    public abstract class CrudDaoBase<T> : DaoBase, ICommonDataBaseActions<T>
        where T : class
    {
        #region Construtor

        public CrudDaoBase()
        {
            this.GetCurrentProvider<T>();
        }

        #endregion

        #region ICommonDataBaseActions<T,TId> Members

        public virtual List<T> GetAll()
        {
            return _provider.GetAll<T>();
        }

        public virtual List<T> GetByCriteria(Criteria crit)
        {
            return _provider.Get<T>(crit);
        }

        public virtual void Create(T obj)
        {
            _provider.Insert<T>(obj);
        }

        public virtual void Update(T obj)
        {
            _provider.Update<T>(obj);
        }

        public virtual int Delete(Criteria crit)
        {
            return _provider.Delete<T>(crit);
        }

        public virtual int Count()
        {
            return _provider.Count<T>();
        }

        public virtual int Count(Criteria crit)
        {
            return _provider.Count<T>(crit);
        }

        public virtual bool Exists(Criteria crit)
        {
            return _provider.Exists<T>(crit);
        }

        public virtual bool HasRows()
        {
            return _provider.Exists<T>();
        }

        #endregion
    }
}
