/*********************************************
Generated by Intentor.Yamapper Class Generator
http://intentor.com.br/projects/yamapper/
*********************************************/
using System;
using System.Collections.Generic;
using Intentor.Yamapper;

namespace Intentor.Examples.Model.Data.Supertypes
{	
	/// <summary>Supertype para Data Access Objects (Dao) somente leitura, utilizados para Views.</summary>
    /// <typeparam name="T">Tipo da entidade que representa a view do banco de dados.</typeparam>
    public abstract class ViewDaoBase<T> : DaoBase
        where T : class
    {
        #region Construtor

        public ViewDaoBase()
        {
            this.GetCurrentProvider<T>();
        }

        #endregion

        #region Métodos

        public virtual List<T> GetAll()
        {
            return _provider.GetAll<T>();
        }

        public virtual List<T> GetByCriteria(Criteria crit)
        {
            return _provider.Get<T>(crit);
        }

        public virtual int Count()
        {
            return _provider.Count<T>();
        }

        public virtual int Count(Criteria crit)
        {
            return _provider.Count<T>(crit);
        }

        public virtual bool Exists(Criteria crit)
        {
            return _provider.Exists<T>(crit);
        }

        public virtual bool HasRows()
        {
            return _provider.Exists<T>();
        }

        #endregion
    }
}
