/******************************************
Generated by Intentor.Yamapper Class Generator
http://intentor.com.br/projects/yamapper/
******************************************/
using System;
using System.Collections.Generic;
using Intentor.Examples.Model.Core.Entities;

namespace Intentor.Examples.Model.Core.DataInterfaces
{	
	/// <summary>
	/// Data interface IClienteProdutoRepository utilizada para métodos customizados.
	/// </summary>
	public partial interface IClienteProdutoRepository
	{
	
	}
}