/******************************************
Generated by Intentor.Yamapper Class Generator
http://intentor.com.br/projects/yamapper/
******************************************/
using System;
using System.Collections.Generic;
using System.Linq;
using Intentor.Yamapper;
using Intentor.Examples.Model.Core.DataInterfaces;
using Intentor.Examples.Model.Core.Entities;
using Intentor.Examples.Model.Data;
using Intentor.Utilities;

namespace Intentor.Examples.Model.Domain
{	
	/// <summary>
	/// Business Object ClienteBiz utilizada para métodos customizados.
	/// </summary>
	public partial class ClienteBiz
	{
        public List<Cliente> GetClientesOrderedByName()
        {
            return _dao.GetByCriteria(Criteria.Create()
                .AddOrder(Order.ASC("Nome")));
        }

        public List<Cliente> GetClientesNomesComJ()
        {
            return _dao.GetByCriteria(Criteria.Create()
                .Add(Expression.Sql("Nome LIKE {param}", "%J%")));
        }

        public List<Cliente> GetClientesComCertosNomes()
        {
            return _dao.GetByCriteria(Criteria.Create()
                .Add(Expression.In<string>("Nome", new string[] { "João", "José", "Josisbaldo" }))
                .AddOrder("Nome"));
        }

        public List<Cliente> GetClientesComCertosNomes2()
        {
            /* Exemplo de aninhamento de expressões AND/OR.
             * O resultado é equivalente a

                    SELECT *
                    FROM tbCliente
                    WHERE 
                        (
                            (Nome = 'João' AND DataCadastro IS NOT NULL)
                            OR
                            (Nome = 'José'  AND DataCadastro IS NOT NULL)
                            OR
                            (Nome = 'Josisbaldo' AND DataCadastro IS NOT NULL)
                        )
             */
            return _dao.GetByCriteria(Criteria.Create()
                .Add(Expression.Or(
                    Expression.And(
                        Expression.Equal("Nome", "João"),
                        Expression.IsNotNull("DataCadastro"))
                    , Expression.And(
                        Expression.Equal("Nome", "José"),
                        Expression.IsNotNull("DataCadastro"))
                    , Expression.And(
                        Expression.Equal("Nome", "Josisbaldo"),
                        Expression.IsNotNull("DataCadastro")))));
        }
	}
}