/******************************************
Generated by Intentor.Yamapper Class Generator
http://intentor.com.br/projects/yamapper/
******************************************/
using System;
using System.Collections.Generic;
using System.Linq;
using Intentor.Yamapper;
using Intentor.Examples.Model.Core.DataInterfaces;
using Intentor.Examples.Model.Core.Entities;
using Intentor.Examples.Model.Data;

namespace Intentor.Examples.Model.Domain
{	
	/// <summary>
	/// Business Object ClienteProdutoBiz utilizada para métodos customizados.
	/// </summary>
	public partial class ClienteProdutoBiz
	{
		
	}
}