/******************************************
Generated by Intentor.Yamapper Class Generator
http://intentor.com.br/projects/yamapper/
******************************************/
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using Intentor.Utilities;
using Intentor.Yamapper;
using Intentor.Examples.Model.Core.Entities;

namespace Intentor.Examples.Model.Data
{	
	/// <summary>
	/// Data Access Object ProdutoDao utilizada para métodos customizados.
	/// </summary>
	public sealed partial class ProdutoDao
	{		
		
	}
}