/*********************************************
Generated by Intentor.Yamapper Class Generator
http://intentor.com.br/projects/yamapper/
*********************************************/
using System;
using System.ComponentModel.DataAnnotations;
using Intentor.Yamapper;

namespace Intentor.Examples.Model.Core.Entities
{	
	/// <summary></summary>
	/// <remarks>Mapeada de tbCliente.</remarks>	
	[Serializable]
	public class Cliente
	{
		[Required]
		[Display(Name = "IdCliente", Description = "")]
		public virtual int IdCliente { get; set; }

		[Required]
		[StringLength(100)]
		[Display(Name = "Nome", Description = "")]
		public virtual string Nome { get; set; }

		[Display(Name = "DataCadastro", Description = "")]
		public virtual DateTime? DataCadastro { get; set; }

		[Required]
		[Display(Name = "Informativos", Description = "")]
		public virtual bool Informativos { get; set; }
	}
}