/*********************************************
Generated by Intentor.Yamapper Class Generator
http://intentor.com.br/projects/yamapper/
*********************************************/
using System;
using System.ComponentModel.DataAnnotations;
using Intentor.Yamapper;

namespace Intentor.Examples.Model.Core.Entities
{	
	/// <summary></summary>
	/// <remarks>Mapeada de tbClienteProduto.</remarks>	
	[Serializable]
	public class ClienteProduto
	{
		[Required]
		[Display(Name = "IdCliente", Description = "")]
		public virtual int IdCliente { get; set; }

		[Required]
		[Display(Name = "IdProduto", Description = "")]
		public virtual int IdProduto { get; set; }
	}
}