/*********************************************
Generated by Intentor.Yamapper Class Generator
http://intentor.com.br/projects/yamapper/
*********************************************/
using System;
using System.ComponentModel.DataAnnotations;
using Intentor.Yamapper;

namespace Intentor.Examples.Model.Core.Entities
{	
	/// <summary></summary>
	/// <remarks>Mapeada de tbProduto.</remarks>	
	[Serializable]
	public class Produto
	{
		[Required]
		[Display(Name = "IdProduto", Description = "")]
		public virtual int IdProduto { get; set; }

		[Required]
		[StringLength(100)]
		[Display(Name = "Nome", Description = "")]
		public virtual string Nome { get; set; }
	}
}